// <auto-generated />
namespace Anzu.AnnPortal.Data.EntityManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class R15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(R15));
        
        string IMigrationMetadata.Id
        {
            get { return "201702140617247_R15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
