// <auto-generated />
namespace Anzu.AnnPortal.Data.EntityManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class R26 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(R26));
        
        string IMigrationMetadata.Id
        {
            get { return "201707170327117_R26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
